Added four Python examples
Lotame/api-examples pull request #2
Opened 2017-06-06 17:26 UTC by bmcoker

2017-06-06 18:14 UTC, singhald requested changes

2017-06-06 18:14 UTC, singhald commented on py/audience_creation_example.py
> +        'generate_apr': True,  # Be sure to set whether APR should be enabled
I'm tempted to recommend we set this to False, so the default script doesn't activate APRs . it's a trivial change to update it to do so, for the user, at that point, but by default?

2017-06-06 18:14 UTC, singhald commented on py/uncategorized_behavior_report.py
> +    Generates an uncategorized beahvior report for IBM - Network and saves it
should probably remove the IBM comment and make it generic

2017-06-06 18:14 UTC, singhald commented on py/uncategorized_behavior_report.py
> +    endpoint = 'reports/behaviors/uncategorized?client_id=' + \
I'm hoping to start deprecating this endpoint, so lets direct people to the newer one:

https://api.lotame.com/2/behaviors/search/elastic?client_id=25&owner=OWNER&active=ACTIVE_ONLY&categorized=UNCATEGORIZED_ONLY&ignored=NON_IGNORED_ONLY&categorizable=CATEGORIZABLE_ONLY&date_range=LAST_30_DAYS&page_count=50&page_num=1&sort_attr=id&sort_order=ASC&appendNetworkClients=false&clientAsGroup=true

?

(little bit of re-writing then for the different format but faster!)


@sromack or should we leave this example out until we can merge the /search and /search/elastic into a single /search again?

2017-06-06 18:15 UTC, bmcoker commented on py/audience_creation_example.py
> +        'generate_apr': True,  # Be sure to set whether APR should be enabled
Fair enough, it's a good point and I can change that.

2017-06-06 18:15 UTC, bmcoker commented on py/uncategorized_behavior_report.py
> +    Generates an uncategorized beahvior report for IBM - Network and saves it
Whoops, you're totally right on this. I wrote this example for IBM and thought I scrubbed all of that out.

2017-06-07 12:23 UTC, bmcoker commented on py/uncategorized_behavior_report.py
> +    endpoint = 'reports/behaviors/uncategorized?client_id=' + \
I'll remove this file for now.

2017-06-07 13:24 UTC, singhald approved these changes

2017-06-28 21:00 UTC, sromack commented on py/audience_creation_example.py
> +def create_behavior_definition(tgt, behavior_id, relationship):
Why do you need the tgt here?

2017-06-28 21:01 UTC, sromack commented on py/audience_creation_example.py
> +    behaviors = []
Seem like this would be clearer if you named this behavior_definitions.

2017-06-29 15:54 UTC, bmcoker commented on py/audience_creation_example.py
> +def create_behavior_definition(tgt, behavior_id, relationship):
You know, I've gotta be honest, I'm not sure. I think I might have previously used it to GET /behaviors/{behavior_id}, back when I thought I needed to get the behavior name in order to create the JSON. Will fix, thanks.

2017-06-29 15:54 UTC, bmcoker commented on py/audience_creation_example.py
> +    behaviors = []
Can do.

2017-06-29 15:57 UTC, bmcoker reviewed
Made requested changes to audience_creation_example.py.

2017-06-29 17:11 UTC, sromack commented on py/audience_creation_example.py
> +    for behavior_id in behavior_definitions:
Oops. Sorry about missing confusing which was which. I thought behavior_definitions made sense to contain the actual json for the behavior (the return from create_behavior_definition call). The one that just contains ids probably should just be behavior_ids or something similar.

2017-06-29 17:12 UTC, sromack approved these changes

2017-06-29 17:21 UTC, singhald commented
aside from summer making you play yoyo with the variable names, looks good to me again/still

2017-06-29 17:23 UTC, bmcoker commented
Alright. Reverted the variable names, so all should be good to go now.

2017-06-29 17:24 UTC, bmcoker commented
Oops I closed the request 😅

2017-06-29 17:24 UTC, sromack approved these changes

2017-06-29 17:26 UTC, sromack commented
Sorry about that. I just misplaced my comment - meant to say the "behaviors" array should be renamed to "behavior_definitions" but this is fine. Forget I said anything :P

2017-07-10 12:24 UTC, bmcoker commented
@sromack Is this good to be merged?

2017-07-10 13:51 UTC, sromack approved these changes

2017-08-16 19:32 UTC, bmcoker commented
@sromack Any chance we can get this merged?

2017-08-22 15:21 UTC, merged